# Generated by Django 3.0b1 on 2019-11-28 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='album_title',
            new_name='button1',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='genre',
            new_name='button2',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='artist',
            new_name='question_text',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='album_logo',
            new_name='video_file',
        ),
    ]
