# Generated by Django 3.0b1 on 2019-11-28 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0002_auto_20191128_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
