# Generated by Django 3.0b1 on 2019-11-28 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0003_video_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='button1',
            field=models.CharField(max_length=100),
        ),
    ]
