# Generated by Django 3.0b1 on 2019-12-01 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0005_choice_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='choice_num',
            field=models.IntegerField(default=1),
        ),
    ]
