# Generated by Django 3.0b1 on 2019-12-06 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0006_choice_choice_num'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
        migrations.RenameField(
            model_name='choice',
            old_name='votes',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='question',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='question',
            name='custom_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='question',
            name='timestamp',
            field=models.FloatField(default=1.0),
        ),
    ]
