# Generated by Django 3.0b1 on 2019-12-08 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0007_auto_20191206_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(max_length=97),
        ),
    ]
