# Generated by Django 3.0b1 on 2019-12-09 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0008_auto_20191208_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='choice1_text',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='choice2_text',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='price1',
            field=models.IntegerField(default=0),
        ),
    ]
