# Generated by Django 3.0b1 on 2019-12-09 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0009_auto_20191209_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='skip_to',
            field=models.FloatField(default=1.0),
        ),
    ]
