# Generated by Django 3.0b1 on 2019-12-10 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0010_question_skip_to'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='price',
            new_name='price2',
        ),
        migrations.AddField(
            model_name='question',
            name='choice1_skiptime',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='question',
            name='choice1_timestamp',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='question',
            name='choice1_text',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='question',
            name='choice2_text',
            field=models.CharField(max_length=10),
        ),
    ]
