# Generated by Django 3.0b1 on 2019-12-10 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play', '0011_auto_20191210_0240'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='choice2_skiptime',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='question',
            name='choice2_timestamp',
            field=models.FloatField(default=1.0),
        ),
    ]
